watch_stylesheet: true
watch_config: true
debug: false
update_check: true
bars:
  primary-bar:
    enabled: true
    screens: ["primary"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 400
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
      round_corners_type: "normal"
      border_color: "system"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 36
    widgets:
      left:
      - "glazewm_workspaces"
      - "cpu"
      - "gpu"
      - "memory"
      center:
      - "clock"
      right:
      # - "media"
      # - "volume"
      # - "microphone"
      # - "wifi"
widgets:
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: false
      hide_if_offline: false
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      update_interval: 4000
      callbacks:
        on_left: "exec cmd /c Taskmgr"
        on_middle: "do_nothing"
        on_right: "do_nothing"
  gpu:
    type: "yasb.gpu.GpuWidget"
    options:
      label: "<span>\uf26c</span> {info[utilization]}%"
      label_alt: "<span>\uf26c</span> {info[temp]}Â°C | {info[mem_used]} / {info[mem_total]}"
      update_interval: 4000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
  memory:
      type: "yasb.memory.MemoryWidget"
      options:
        label: "<span>\uefc5</span> {virtual_mem_percent}%"
        label_alt: "<span>\uefc5</span> {virtual_mem_used} / {virtual_mem_total}"
        update_interval: 8000
        callbacks:
          on_left: "toggle_label"
          on_middle: "do_nothing"
          on_right: "do_nothing"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a | %d. %b | %H:%M}"
      timezones: []
      calendar:
        blur: false
        round_corners: false
        alignment: "center"
        direction: "down"
      callbacks:
        on_left: "toggle_calendar"
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      label_alt: "{artist} - {title}"
      max_field_size:
        label: 16
        label_alt: 24
      show_thumbnail: true
      controls_only: false
      controls_left: true
      controls_hide: true
      hide_empty: true
      thumbnail_alpha: 100
      thumbnail_padding: 16
      thumbnail_corner_radius: 0
      thumbnail_edge_fade: true
      icons:
        prev_track: "\udb81\udcae"
        next_track: "\udb81\udcad"
        play: "\udb81\udc0a"
        pause: "\udb80\udfe4"
      media_menu:
        blur: false
        round_corners: false
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 4
        thumbnail_size: 100
        max_title_size: 80
        max_artist_size: 20
        show_source: true
      label_shadow:
        enabled: true
        color: "#000000"
        radius: 2
        offset: [ 1, 1 ]
      scrolling_label:
        enabled: true
        update_interval_ms: 50
        style: "left"  # can be "left", "right", "bounce", "bounce-ease"
        separator: " | "
        label_padding: 1
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      tooltip: false
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_left: "toggle_mute"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "<span>{icon}</span> {level}%"
      icons:
        normal: "\udb80\udf6c"
        muted: "\udb80\udf6d"
      callbacks:
        on_left: "toggle_mute"
        on_middle: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
