watch_stylesheet: true
watch_config: true
debug: false
update_check: true
bars:
  primary-bar:
    enabled: true
    screens: ["primary"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 400
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
      round_corners_type: "normal"
      border_color: "system"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 36
    widgets:
      left:
      - "glazewm_workspaces"
      - "cpu"
      - "gpu"
      - "memory"
      center:
      - "active_window"
      right:
      # - "media"
      # - "weather"
      # - "user"
widgets:
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: false
      hide_if_offline: false
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      update_interval: 4000
      callbacks:
        on_left: "exec cmd /c Taskmgr"
        on_middle: "do_nothing"
        on_right: "do_nothing"
  gpu:
    type: "yasb.gpu.GpuWidget"
    options:
      label: "<span>\uf26c</span> {info[utilization]}%"
      label_alt: "<span>\uf26c</span> {info[temp]}Â°C | {info[mem_used]} / {info[mem_total]}"
      update_interval: 4000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
  memory:
      type: "yasb.memory.MemoryWidget"
      options:
        label: "<span>\uefc5</span> {virtual_mem_percent}%"
        label_alt: "<span>\uefc5</span> {virtual_mem_used} / {virtual_mem_total}"
        update_interval: 8000
        callbacks:
          on_left: "toggle_label"
          on_middle: "do_nothing"
          on_right: "do_nothing"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[process][name]}"
      label_alt: "{win[title]}"
      label_no_window: ""
      label_icon: true
      label_icon_size: 18
      max_length: 56
      max_length_ellipsis: "..."
      monitor_exclusive: false
      rewrite:
        - pattern: "^(.+?)\\.exe$"
          replacement: "\\1"
