watch_stylesheet: true
watch_config: true
debug: false
update_check: true
bars:
  primary-bar:
    enabled: true
    screens: ["primary"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 400
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
      round_corners_type: "normal"
      border_color: "system"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 36
    widgets:
      left:
      - "glazewm_workspaces"
      - "cpu"
      - "gpu"
      - "memory"
      center:
      - "active_window"
      right:
      - "media"
      - "weather"
      - "user_host"
widgets:
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: false
      hide_if_offline: false
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      update_interval: 4000
      callbacks:
        on_left: "exec cmd /c Taskmgr"
        on_middle: "do_nothing"
        on_right: "do_nothing"
  gpu:
    type: "yasb.gpu.GpuWidget"
    options:
      label: "<span>\uf26c</span> {info[utilization]}%"
      label_alt: "<span>\uf26c</span> {info[temp]}Â°C | {info[mem_used]} / {info[mem_total]}"
      update_interval: 4000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
  memory:
      type: "yasb.memory.MemoryWidget"
      options:
        label: "<span>\uefc5</span> {virtual_mem_percent}%"
        label_alt: "<span>\uefc5</span> {virtual_mem_used} / {virtual_mem_total}"
        update_interval: 8000
        callbacks:
          on_left: "toggle_label"
          on_middle: "do_nothing"
          on_right: "do_nothing"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[process][name]}"
      label_alt: "{win[title]}"
      label_no_window: ""
      label_icon: true
      label_icon_size: 18
      max_length: 56
      max_length_ellipsis: "..."
      monitor_exclusive: false
      rewrite:
        - pattern: "^(.+?)\\.exe$"
          replacement: "\\1"
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      max_field_size:
        label: 20
      show_thumbnail: false
      controls_only: false
      controls_left: true
      icons:
        prev_track: "\uf048"
        next_track: "\uf051"
        play: "\uf04b"
        pause: "\uf04c"
      scrolling_label:
        enabled: true
        update_interval_ms: 30
        style: "left"
        separator: " | "
        label_padding: 10
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 60
        thumbnail_corner_radius: 8
        thumbnail_size: 120
        max_title_size: 27
        max_artist_size: 60
        show_source: true
      media_menu_icons:
        prev_track: "\uf048"
        next_track: "\uf051"
        play: "\uf04b"
        pause: "\uf04c"
      callbacks:
        on_left: "toggle_play_pause"
        on_middle: "do_nothing"
        on_right: "toggle_media_menu"
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp} | {location}"
      label_alt: "Min. {min_temp} | Max. {max_temp} | Humidity {humidity}"
      api_key: 'a82399e9a0fb4f8ea1d73504250912' # free api-key from weatherapi.com
      update_interval: 600
      hide_decimal: true
      tooltip: false
      location: 'Germany Krefeld 47807'
      callbacks:
        on_left: "toggle_label"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\udb81\udd94"
        cloudyDay: "\uebaa"
        cloudyNight: "\uebaa"
        rainyDay: "\udb81\udd96"
        rainyNight: "\udb81\udd96"
        snowyIcyDay: "\udb81\udd92"
        snowyIcyNight: "\udb81\udd92"
        blizzardDay: "\udb81\udd93"
        default: "\uebaa"
  user_host:
    type: "yasb.custom.CustomWidget"
    options:
      label: "{data}"
      label_alt: "{data}"
      class_name: "user-host-widget"
      exec_options:
        run_cmd: "powershell -Command \"$env:USERNAME@$env:COMPUTERNAME\""
        run_interval: 300000
        return_format: "string"
        hide_empty: false
      callbacks:
        on_left: "do_nothing"
        on_middle: "do_nothing"
        on_right: "do_nothing"
